name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: make lint
      - name: Run unit tests
        run: make test
